services:
    viweb_contact.admin_menu_listener:
        class: Viweb\ContactBundle\EventListener\ConfigureAdminMenuListener
        tags:
          - { name: kernel.event_listener, event: viweb_system.menu_admin_configure, method: onMenuConfigure }