<?php

namespace Viweb\ContactBundle\Repository;

/**
 * ContactContainerTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactContainerTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
